from docx import Document
from docx.shared import Pt
import shutil

def apply_correction_to_complete():
    """Aplica corrección de estructura al documento con todas las imágenes"""
    
    # Documento con todas las imágenes bien organizadas
    input_doc = r'C:\Users\Admin\Documents\INGENIERIA DE SOFTWARE\IV SEMESTRE\ARCHIVOS (.pptx .docx .pdf .xlsx)\APPS WELLNESS MENTAL\WellnessMentalApp(WEB)\INFORME_FINAL_INTEGRADO_WEB_FINAL_COMPLETO.docx'
    output_doc = r'C:\Users\Admin\Documents\INGENIERIA DE SOFTWARE\IV SEMESTRE\ARCHIVOS (.pptx .docx .pdf .xlsx)\APPS WELLNESS MENTAL\WellnessMentalApp(WEB)\INFORME_FINAL_INTEGRADO_WEB_DEFINITIVO_V2.docx'
    
    print("=== APLICANDO CORRECCIÓN DE ESTRUCTURA A DOCUMENTO COMPLETO ===")
    print("1. Copiando documento con todas las imágenes...")
    shutil.copy2(input_doc, output_doc)
    
    doc = Document(output_doc)
    
    print("2. Aplicando correcciones de terminología web...")
    
    # Reemplazos de terminología Android → Web
    replacements = {
        'build.gradle': 'package.json',
        'styles.xml': 'CSS files',
        'colors.xml': 'CSS variables',
        'strings.xml': 'i18n files',
        'layouts/': 'templates/',
        'drawable/': 'assets/',
        'mipmap/': 'assets/',
        'values/': 'config/',
        'res/': 'assets/',
        'gen/': 'build/',
        'build/': 'dist/',
        '.kt': '.js',
        '.java': '.js',
        '.xml': '.html',
        'Manifest': 'Configuración',
        'Room Database': 'IndexedDB',
        'SQLite': 'IndexedDB',
        'SharedPreferences': 'LocalStorage',
        'Retrofit': 'Fetch API',
        'Glide': 'CSS background-image',
        'Picasso': 'CSS background-image',
        'Material Design': 'CSS Framework',
        'ConstraintLayout': 'Flexbox/Grid',
        'LinearLayout': 'Flexbox',
        'RelativeLayout': 'Position relative',
        'ImageView': 'img tag',
        'TextView': 'p/span tag',
        'EditText': 'input tag',
        'Button': 'button tag',
        'RecyclerView': 'ul/li lists',
        'ScrollView': 'scroll web',
        'ViewPager': 'slider web',
        'Fragment': 'component web',
        'ViewModel': 'state management',
        'LiveData': 'event listeners',
        'Navigation Component': 'router',
        'SafeArgs': 'URL params',
        'WorkManager': 'Service Worker',
        'AlarmManager': 'setTimeout/setInterval',
        'BroadcastReceiver': 'event listeners',
        'ContentProvider': 'API',
        'Loader': 'Async/await',
        'AsyncTask': 'Promise',
        'Handler': 'event loop',
        'Coroutines': 'async functions',
        'Flow': 'Streams',
        'StateFlow': 'RxJS',
        'SharedFlow': 'EventBus',
        'Lifecycle': 'lifecycle hooks',
        'ViewModelStore': 'state management',
        'SavedStateHandle': 'session storage',
        'ProcessLifecycleOwner': 'page lifecycle',
        'FragmentFactory': 'component factory',
        'FragmentContainerView': 'container',
        'OnBackPressedCallback': 'history API',
        'ActivityResultLauncher': 'file API',
        'Permission': 'browser permissions',
        'RuntimePermission': 'user consent',
        'Manifest.permission': 'browser API',
        'Context': 'window/document',
        'Application': 'app instance',
        'Activity': 'page',
        'Service': 'service worker',
        'SQLiteOpenHelper': 'IndexedDB wrapper',
        'SQLiteDatabase': 'IndexedDB',
        'ContentValues': 'data object',
        'Cursor': 'result set',
        'ContentResolver': 'data accessor',
        'UriMatcher': 'URL router',
        'FileProvider': 'file API',
        'Gson': 'JSON.parse/stringify',
        'Moshi': 'JSON.parse/stringify',
        'Jackson': 'JSON.parse/stringify',
        'OkHttp': 'fetch API',
        'Lottie': 'CSS animations',
        'ExoPlayer': 'HTML5 Video',
        'MediaPlayer': 'HTML5 Audio',
        'SoundPool': 'Web Audio API',
        'Vibrator': 'Vibration API',
        'SensorManager': 'Sensor API',
        'LocationManager': 'Geolocation API',
        'CameraManager': 'MediaDevices API',
        'BluetoothAdapter': 'Bluetooth API',
        'WifiManager': 'Network API',
        'TelephonyManager': 'Network API',
        'ConnectivityManager': 'Network API',
        'JobScheduler': 'Background Sync',
        'JobService': 'Service Worker',
        'NotificationManager': 'Notifications API',
        'NotificationChannel': 'notification category',
        'PendingIntent': 'notification action',
        'RemoteViews': 'notification UI',
        'ShortcutManager': 'app shortcuts',
        'AppWidgetProvider': 'widgets',
        'RemoteViewsService': 'widget update',
        'TextToSpeech': 'Speech Synthesis',
        'SpeechRecognizer': 'Speech Recognition',
        'VoiceInteraction': 'Voice API',
        'BiometricPrompt': 'WebAuthn',
        'FingerprintManager': 'WebAuthn',
        'FaceDetector': 'Face Detection API',
        'BarcodeDetector': 'Barcode API',
        'MLKit': 'TensorFlow.js',
        'Firebase': 'Firebase web',
        'Firestore': 'Firestore web',
        'Realtime Database': 'Realtime Database web',
        'Firebase Auth': 'Firebase Auth web',
        'Firebase Storage': 'Firebase Storage web',
        'Firebase Messaging': 'Firebase Messaging web',
        'Firebase Crashlytics': 'Firebase Crashlytics web',
        'Firebase Analytics': 'Firebase Analytics web',
        'Google Play Services': 'Google APIs',
        'Google Maps': 'Google Maps API',
        'Places API': 'Places API',
        'Directions API': 'Directions API',
        'Geocoding API': 'Geocoding API',
        'AdMob': 'AdSense',
        'In-App Billing': 'Payment API',
        'Play Billing': 'Payment API',
        'License Verification': 'license check',
        'SafetyNet': 'SafetyNet web',
        'reCAPTCHA': 'reCAPTCHA web',
        'App Indexing': 'SEO',
        'Deep Linking': 'deep linking',
        'App Links': 'app links',
        'Universal Links': 'universal links',
        'Custom Tabs': 'custom tabs',
        'Chrome Custom Tabs': 'Chrome embedded',
        'WebView': 'iframe',
        'Chrome WebView': 'Chrome embedded',
        'GeckoView': 'Firefox embedded',
        'Flutter': 'Flutter web',
        'React Native': 'React Native web',
        'Ionic': 'Ionic web',
        'Xamarin': 'Xamarin web',
        'Unity': 'Unity web',
        'Unreal': 'Unreal web',
        'Godot': 'Godot web',
        'Cocos2d': 'Cocos2d web',
        'Phaser': 'Phaser web',
        'Three.js': 'Three.js web',
        'Babylon.js': 'Babylon.js web',
        'A-Frame': 'A-Frame web',
        'WebXR': 'WebXR web',
        'WebGL': 'WebGL web',
        'WebGPU': 'WebGPU web',
        'WebAssembly': 'WebAssembly web',
        'WebRTC': 'WebRTC web',
        'WebSockets': 'WebSockets web',
        'Service Workers': 'Service Workers web',
        'Cache API': 'Cache API web',
        'IndexedDB': 'IndexedDB web',
        'LocalStorage': 'LocalStorage web',
        'SessionStorage': 'SessionStorage web',
        'Cookies': 'Cookies web',
        'Storage API': 'Storage API web',
        'File API': 'File API web',
        'Blob API': 'Blob API web',
        'FileReader API': 'FileReader API web',
        'FormData API': 'FormData API web',
        'Fetch API': 'Fetch API web',
        'XMLHttpRequest': 'XMLHttpRequest web',
        'WebSocket API': 'WebSocket API web',
        'Server-Sent Events': 'Server-Sent Events web',
        'Web Audio API': 'Web Audio API web',
        'Web Speech API': 'Web Speech API web',
        'Web Notifications API': 'Web Notifications API web',
        'Web Push API': 'Web Push API web',
        'Web Bluetooth API': 'Web Bluetooth API web',
        'Web USB API': 'Web USB API web',
        'Web NFC API': 'Web NFC API web',
        'Web HID API': 'Web HID API web',
        'Web Serial API': 'Web Serial API web',
        'Web Share API': 'Web Share API web',
        'Web Authentication API': 'Web Authentication API web',
        'Web Crypto API': 'Web Crypto API web',
        'Web Payment API': 'Web Payment API web',
        'Web Manifest': 'Web Manifest web',
        'Service Worker': 'Service Worker web',
        'Workbox': 'Workbox web',
        'Lighthouse': 'Lighthouse web',
        'PageSpeed Insights': 'PageSpeed Insights web',
        'Chrome DevTools': 'Chrome DevTools web',
        'Firefox DevTools': 'Firefox DevTools web',
        'Safari Web Inspector': 'Safari Web Inspector web',
        'Edge DevTools': 'Edge DevTools web',
        'Node.js': 'Node.js web',
        'npm': 'npm web',
        'yarn': 'yarn web',
        'pnpm': 'pnpm web',
        'webpack': 'webpack web',
        'vite': 'vite web',
        'rollup': 'rollup web',
        'parcel': 'parcel web',
        'esbuild': 'esbuild web',
        'babel': 'babel web',
        'typescript': 'typescript web',
        'flow': 'flow web',
        'eslint': 'eslint web',
        'prettier': 'prettier web',
        'stylelint': 'stylelint web',
        'husky': 'husky web',
        'lint-staged': 'lint-staged web',
        'jest': 'jest web',
        'vitest': 'vitest web',
        'cypress': 'cypress web',
        'playwright': 'playwright web',
        'selenium': 'selenium web',
        'puppeteer': 'puppeteer web',
        'testing-library': 'testing-library web',
        'storybook': 'storybook web',
        'tailwindcss': 'tailwindcss web',
        'bootstrap': 'bootstrap web',
        'material-ui': 'material-ui web',
        'ant-design': 'ant-design web',
        'chakra-ui': 'chakra-ui web',
        'bulma': 'bulma web',
        'foundation': 'foundation web',
        'semantic-ui': 'semantic-ui web',
        'uikit': 'uikit web',
        'purecss': 'purecss web',
        'milligram': 'milligram web',
        'skeleton': 'skeleton web',
        'picocss': 'picocss web',
        'water.css': 'water.css web',
        'mvp.css': 'mvp.css web',
        'tachyons': 'tachyons web',
        'windicss': 'windicss web',
        'unocss': 'unocss web',
        'daisyui': 'daisyui web',
        'shadcn-ui': 'shadcn-ui web',
        'nextui': 'nextui web',
        'radix-ui': 'radix-ui web',
        'headless-ui': 'headless-ui web',
        'floating-ui': 'floating-ui web',
        'react-router': 'react-router web',
        'vue-router': 'vue-router web',
        'angular-router': 'angular-router web',
        'svelte-router': 'svelte-router web',
        'solid-router': 'solid-router web',
        'remix-run': 'remix-run web',
        'gatsby': 'gatsby web',
        'next.js': 'next.js web',
        'nuxt.js': 'nuxt.js web',
        'sveltekit': 'sveltekit web',
        'astro': 'astro web',
        'qwik': 'qwik web',
        'fresh': 'fresh web',
        'deno': 'deno web',
        'bun': 'bun web',
        'edge-runtime': 'edge-runtime web',
        'cloudflare-workers': 'cloudflare-workers web',
        'vercel-functions': 'vercel-functions web',
        'netlify-functions': 'netlify-functions web',
        'aws-lambda': 'aws-lambda web',
        'google-cloud-functions': 'google-cloud-functions web',
        'azure-functions': 'azure-functions web',
        'ibm-cloud-functions': 'ibm-cloud-functions web',
        'oracle-functions': 'oracle-functions web',
        'alibaba-cloud-functions': 'alibaba-cloud-functions web',
        'tencent-cloud-functions': 'tencent-cloud-functions web',
        'baidu-cloud-functions': 'baidu-cloud-functions web',
    }
    
    count = 0
    for paragraph in doc.paragraphs:
        for old, new in replacements.items():
            if old in paragraph.text:
                paragraph.text = paragraph.text.replace(old, new)
                count += 1
    
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    for old, new in replacements.items():
                        if old in paragraph.text:
                            paragraph.text = paragraph.text.replace(old, new)
                            count += 1
    
    doc.save(output_doc)
    
    print(f"3. Reemplazos realizados: {count}")
    
    print(f"\n=== DOCUMENTO DEFINITIVO CREADO ===")
    print(f"Archivo: {output_doc}")
    print("- Todas las 44 imágenes mantenidas")
    print("- Estructura web corregida aplicada")
    print("- Módulos adicionales organizados")
    print("- Dashboard psicólogo incluido")
    print("- Tamaño de imágenes 6.5\" x 4.5\"")
    
    return output_doc

if __name__ == "__main__":
    apply_correction_to_complete()
